# build go binary
FROM golang:1.21 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o mq-watch ./cmd/server

# Final stage: Alpine
FROM alpine@sha256:48d9183eb12a05c99bcc0bf44a003607b8e941e1d4f41f9ad12bdcc4b5672f86

WORKDIR /app

# Copy binary
COPY --from=builder /app/mq-watch /app/mq-watch

ENTRYPOINT ["./mq-watch"]
