version: '3'

vars:
  GOOS: "{{OS}}"

tasks:

  test:
    cmds:
      - go test ./...

  build:
    cmds:
      - task: build:{{OS}}

  build:web:
    dir: web
    cmds:
      - npm install
      - npm run build

  copy:web:
    cmds:
      - task: copy:web:{{OS}}
  copy:web:windows:
    cmds:
      - powershell -Command Copy-Item -Path web/dist/* -Destination cmd/server/web/dist/ -Recurse
  copy:web:darwin:
    cmds:
      - cp -r web/dist/* cmd/server/web/dist/
  copy:web:linux:
    cmds:
      - cp -r web/dist/* cmd/server/web/dist/

  build:windows:
    cmds:
      - go env -w CGO_ENABLED=1 GOOS=windows GOARCH=amd64
      - go build -o bin/mq-watch.exe ./cmd/server/main.go

  build:darwin:
    cmds:
      - go env -w CGO_ENABLED=1 GOOS=darwin GOARCH=amd64
      - go build -o bin/mq-watch ./cmd/server/main.go

  build:linux:
    cmds:
      - go env -w CGO_ENABLED=1 GOOS=linux GOARCH=amd64
      - go build -o bin/mq-watch ./cmd/server/main.go

  run:
    cmds:
      - task: build:{{OS}}
      - task: run:{{OS}}
        vars:
          ARGS: "{{.CLI_ARGS}}"

  run:darwin:
    cmds:
      - bin/mq-watch -config examples/config.yaml {{.ARGS}}
  run:linux:
    cmds:
      - bin/mq-watch -config examples/config.yaml {{.ARGS}}
  run:windows:
    cmds:
      - bin/mq-watch.exe -config examples/config.yaml {{.ARGS}}

  lint:
    cmds:
      - golangci-lint run ./... -v --timeout 5m

  scan:
    cmds:
      - gosec -conf .gosec.config.json "./..."

  tools:install:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tools:install:gosec:
    desc: Install gosec
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest

  containers:up:
    cmds:
      - task: containers:up:mosquitto

  containers:up:mosquitto:
    cmds:
      - docker run -d -v $(pwd)/tests/mosquitto.conf:/mosquitto/config/mosquitto.conf -p 1883:1883 --name mosquitto eclipse-mosquitto

  containers:up:postgres:
    cmds:
      - docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=postgres  -e POSTGRES_USER=postgres -e POSTGRES_DB=mq-watch --name postgres postgres:14.0-alpine

  containers:down:
    cmds:
      - docker stop mosquitto
      - docker rm mosquitto

  containers:down:mosquitto:
    cmds:
      - docker stop mosquitto
      - docker rm mosquitto

  containers:down:postgres:
    cmds:
      - docker stop postgres
      - docker rm postgres
