mqtt:
  broker: "mqtt://127.0.0.1:1883"
  client_id: "mq-watch"

tenants:
  - name: "Tenant1"
    topics:
      - "Tenant1/topic1"
      - "Tenant1/topic2"
      - "Tenant1/topic3"
  - name: "Tenant2"
    topics:
      - "Tenant2/topic1"
  - name: "Tenant3"
    topics:
      - "Tenant3/topic1"
  - name: "Tenant4"
    topics:
      - "Tenant4/topic1"
  - name: "Tenant5"
    topics:
      - "Tenant5/topic1"
  - name: "Tenant6"
    topics:
      - "Tenant6/topic1"
  - name: "Tenant7"
    topics:
      - "Tenant7/topic1"
  - name: "Tenant8"
    topics:
      - "Tenant8/topic1"
  - name: "Tenant9"
    topics:
      - "Tenant9/topic1"
  - name: "Tenant10"
    topics:
      - "Tenant10/topic1"

database:
  sqlite:
    enabled: false
    datasource: "mq-watch.db"
    auto_migrate: true
  postgres:
    enabled: true
    host: "127.0.0.1"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "mq-watch"
    auto_migrate: true

server:
  port: 8000
