mqtt:
  broker: "mqtt://127.0.0.1:1883"
  client_id: "my_client_id"

tenants:
  - name: "tenant1"
    topics:
      - "tenant1/#"
  - name: "tenant2"
    topics:
      - "tenant2/#"

database:
  dialect: "sqlite"
  datasource: "mq-watch.db"
  auto_migrate: true

server:
  port: 8000
