{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.domain }}`)
      kind: Rule
      services:
        - name: {{ include "mosquitto.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
